server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Reggou/Springcloud-config.git #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - Springcloud-config
      ####读取分支
      label: main

  #RabbitMq相关配置 spring.rabbitmq.host。。。。
  #刷新全部实例：curl -X POST "http://localhost:3344/actuator/bus-refresh"
  #只刷新指定实例，公式：http://localhost:配置中心的端口号/actuator/bus-refresh/{destination}
  #只刷新指定实例：curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:3355"
  #config-client:3355 注册中心服务名:端口号
  rabbitmq:
    host:
    port: 5672
    username:
    password:


#服务注册到eureka地址
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'